cleolibrary/CLEO5

source/CCustomOpcodeSystem.cpp, source/CScriptEngine.cpp
Argument count error check in 0AB1
=> Error messages updates.

CLEO5.vcxproj.filters, source/CCustomOpcodeSystem.cpp, source/CDebug.h, source/CModuleSystem.cpp, source/CModuleSystem.h, source/CPluginSystem.h, source/CScriptEngine.cpp, source/CSoundSystem.cpp, source/CTextManager.cpp, source/CleoBase.cpp, source/CleoBase.h, source/FileEnumerator.h, source/Singleton.h, source/dllmain.cpp, source/stdafx.h
=> Crucial filepaths handling updates

CHANGELOG.md, README.md, source/CCustomOpcodeSystem.cpp
Added special thanks to readme.
=> Call function opcodes argument count validation

source/CCustomOpcodeSystem.cpp
Fixes crash occurring when asi/cleo plugin who registered ScriptDeleteDelegate is unloaded without unregistered it.
Crash like this is caused for example by CLEO+.cleo on game exit.
=> Fix crash in ScriptDeleteDelegate

cleo_sdk/CLEO.h, source/CScriptEngine.cpp
=> Fixed support of provided custom work dir in path resolving.

source/CCustomOpcodeSystem.cpp, source/CScriptEngine.cpp
Fixes Junior's Urbanize mod script loading error
=> Fix load script path

.github/workflows/main.yml, CHANGELOG.md, CLEO5.vcxproj, CLEO5.vcxproj.filters, README.md, cleo_sdk/CLEO.h, source/CCustomOpcodeSystem.cpp, source/CScriptEngine.cpp, source/CleoBase.cpp, source/CleoBase.h, source/OpcodeInfoDatabase.cpp, source/OpcodeInfoDatabase.h, source/cleo.def, third-party/SimpleJSON/README.md, third-party/SimpleJSON/json.hpp
Printing command names in warning and error messages.
Added CLEO_RegisterCommand export to SDK.
=> Implemented SBL json info support. 

cleo_sdk/CLEO.h, cleo_sdk/CLEO_Utils.h, source/CCustomOpcodeSystem.cpp, source/CScriptEngine.cpp, source/OpcodeInfoDatabase.cpp, source/OpcodeInfoDatabase.h, source/cleo.def
Argument names in error/warning messages:
Loading JSON in new thread to avoid delay in game startup.
=> Display of parameter names in error messages

cleo_plugins/MemoryOperations/MemoryOperations.cpp
First try standard in-game way of resolving path and loading the library, fallback to plain LoadLibrary only when failed.
=> Updates in load_dynamic_library opcode.

source/OpcodeInfoDatabase.cpp
=> Ignoring unsupported commands when loading opcodes database.

.github/workflows/main.yml, .github/workflows/test.yml, CLEO5.vcxproj, CLEO5.vcxproj.filters, README.md, cleo_plugins/Text/CTextManager.cpp, cleo_sdk/CLEO.h, source/CCustomOpcodeSystem.cpp, source/CCustomOpcodeSystem.h, source/CPluginSystem.cpp, source/CPluginSystem.h, source/CScriptEngine.cpp, source/CleoBase.cpp, source/FileEnumerator.h, source/cleo.def
* Removed not existing files from solution. Moved orphaned Plugin SDK files to correct filter group.
* Unified shared portion of github actions for push and release. Fixed doubled triggering plugins build. 
* Renamed CLEO SDK's container from DirectoryList to StringList. 
* Added initialization methods to CCustomOpcodeSystem and CPluginSystem.
* Improved look of cleo log by calling classes initialization manually. 
* Fixed invalid Math plugin filename in readme.
* Simplified plugins loading. Fixed legacy plugins overwriting new plugins.
Log preview:
```
14/06/2024 18:04:00.158 Listing CLEO plugins:
14/06/2024 18:04:00.158  - 'D:\GTA_SA\cleo\cleo_plugins\SA.Audio.cleo'
14/06/2024 18:04:00.158  - 'D:\GTA_SA\cleo\cleo_plugins\SA.DebugUtils.cleo'
14/06/2024 18:04:00.158  - …
```
=> Updates and refactoring

cleo_sdk/CLEO_Utils.h, source/CPluginSystem.cpp, source/CleoBase.cpp
Added missing FindFirstFile handle closing.
StringList creation added as utils function.
=> Fixed listing already skipped duplicate files.

cleo_sdk/CLEO_Utils.h, source/CScriptEngine.cpp
Documentation updates in CLEO_Utils.h
=> Fixed script path info of main.scm

CHANGELOG.md, cleo_sdk/CLEO.h, cleo_sdk/CLEO_Utils.h, source/CCustomOpcodeSystem.h, source/CModuleSystem.h, source/CPluginSystem.h, source/CScriptEngine.cpp, source/CScriptEngine.h, source/CleoBase.h
Fixed full screen detection when displaying message boxes.
Virtual path `userfiles:` shortened to `user:`
Refactors
=> Fixes and refactor

cleo_plugins/FileSystemOperations/FileSystemOperations.cpp
Added input parameter checks similar to already used in other places.
Unit tests working.
=> Updated validation of file handle input parameter.

CHANGELOG.md, cleo_plugins/Audio/Audio.vcxproj, cleo_plugins/Audio/Audio.vcxproj.filters, cleo_plugins/DebugUtils/DebugUtils.vcxproj, cleo_plugins/DebugUtils/DebugUtils.vcxproj.filters, cleo_plugins/Text/CTextManager.cpp, cleo_plugins/Text/Text.vcxproj, cleo_plugins/Text/Text.vcxproj.filters, cleo_sdk/CLEO_Utils.h
=> Forbidden filesystem opcodes from accessing outside game locations.

cleo_plugins/Audio/Audio.cpp, cleo_plugins/Audio/CAudioStream.cpp, cleo_plugins/Audio/CAudioStream.h
Fixed mismatch of virtual function name.
=> Fixed set_audio_stream_source_size opcode not working

cleo_plugins/DebugUtils/SA.DebugUtils.ini, cleo_plugins/DebugUtils/ScreenLog.cpp, cleo_plugins/DebugUtils/ScreenLog.h
Increased debug font size and proportions.
=> Added debug prints colors and font style to config file.

tests/.cleo_tests_runner.txt
Use named variables and functions.
=> Tests runner script updated to current SBL.

cleo_plugins/DebugUtils/DebugUtils.cpp, cleo_plugins/DebugUtils/SA.DebugUtils.ini, cleo_plugins/DebugUtils/ScriptLog.h
Added support of 0 argument for disabling the limit.
=> Fix command limit checking for PluginSDK called commands.

source/CScriptEngine.cpp
=> Fix CLEO modules path

source/CCustomOpcodeSystem.cpp, source/CScriptEngine.cpp, source/CScriptEngine.h
=> Add error on missing terminate_script command

cleo_sdk/CLEO.h, examples/Free_ID_Lister.txt, examples/Homie_Help.txt, examples/Limits_Info.txt, examples/Skin_Selector.txt, examples/Train_Spawner.txt
Fixed example scripts to follow function argument type grammar rules.
=> SDK Comments updated. Example scripts refactor.

source/CleoBase.cpp, source/stdafx.h
=> Added support for PortableGTA.asi

cleo_plugins/Audio/CAudioStream.cpp, cleo_plugins/Audio/CSoundSystem.h, cleo_plugins/Audio/SA.Audio.ini, examples/Button_Sound.txt, examples/CLEO_Sound_Button.txt
Introduced stream type UserInterface - following game's SFX volume but not affected by simulation time speed.
Music stream type no longer affected by game speed. (vanilla in-game music is muted while slow motion is used)
None stream type no longer affected by game speed. This is type assigned by default to CLEO audio from scripts in compatibility mode.
=> Introduced UserInterface type of AudioStream.

.github/workflows/add-job-output.js, .github/workflows/job-output.js, .github/workflows/tag-custom-build.js, .github/workflows/test.yml, .github/workflows/version.js
names an output zip using the project version and commit SHA. e.g. SA.CLEO_v5.0.1-35aa32b.zip
=> name custom ci build using version and commit sha

CHANGELOG.md, source/CScriptEngine.cpp
=> Fix Ramdisk and symlink filepath problems in CCustomScript constructor.

CHANGELOG.md, source/CleoBase.cpp
=> fix audio playback in SAMP

.github/workflows/nightly.yml
this workflow should update this release https://github.com/cleolibrary/CLEO5/releases/tag/nightly every night with new updates.
useful for early adopters to reference the latest changes
=> nightly build

CLEO5.vcxproj, CLEO5.vcxproj.filters, cleo_plugins/CLEO_Plugins.sln, cleo_plugins/GameEntities/GameEntities.cpp, cleo_plugins/GameEntities/GameEntities.vcxproj, cleo_plugins/GameEntities/GameEntities.vcxproj.filters, cleo_sdk/CLEO_Utils.h, source/CCustomOpcodeSystem.cpp, source/CGameMenu.cpp, source/CGameMenu.h, source/CGameVersionManager.cpp, source/CGameVersionManager.h, source/CScriptEngine.cpp, source/CScriptEngine.h, source/CleoBase.cpp, source/stdafx.h, tests/.cleo_tests_runner.txt, tests/cleo_tests/GameEntities/0AB5.txt, tests/cleo_tests/GameEntities/0AB6.txt, tests/cleo_tests/GameEntities/0AB7.txt, tests/cleo_tests/GameEntities/0AB8.txt, tests/cleo_tests/GameEntities/0ABD.txt, tests/cleo_tests/GameEntities/0ABE.txt, tests/cleo_tests/GameEntities/0ABF.txt, tests/cleo_tests/GameEntities/0AD2.txt, tests/cleo_tests/GameEntities/0ADD.txt, tests/cleo_tests/GameEntities/0AE1.txt, tests/cleo_tests/GameEntities/0AE2.txt, tests/cleo_tests/GameEntities/0AE3.txt, tests/cleo_tests/cleo_tester.inc
Moving random opcodes from CLEO core to separated plugin.
=> Game entities plugin

source/CCustomOpcodeSystem.cpp, source/CScriptEngine.cpp
All is already handled by CCustomScript constructor.
=> Fixed repeated setting script's debug and compat mode.

CLEO5.vcxproj
Enabled warnings as errors.
Suppressed warning 4073 from Plugin SDK files.
=> Fix warnings.

source/CCustomOpcodeSystem.cpp, source/CDebug.cpp, source/CGameMenu.cpp, source/CModuleSystem.cpp, source/CModuleSystem.h, source/CPluginSystem.cpp, source/CScriptEngine.cpp, source/CleoBase.cpp, source/OpcodeInfoDatabase.cpp, source/ScmFunction.cpp, source/ScmFunction.h, source/crc32.cpp, source/dllmain.cpp, source/exports.cpp
=> Removed unnecessary includes.

CLEO5.vcxproj, cleo_plugins/Audio/Audio.vcxproj, cleo_plugins/DebugUtils/DebugUtils.vcxproj, cleo_plugins/FileSystemOperations/FileSystemOperations.vcxproj, cleo_plugins/GameEntities/GameEntities.vcxproj, cleo_plugins/IniFiles/IniFiles.vcxproj, cleo_plugins/Math/Math.vcxproj, cleo_plugins/MemoryOperations/MemoryOperations.vcxproj, cleo_plugins/Text/Text.vcxproj
Divide compilation time by number of cores.
=> Enabled multi-processor compilation

cleo_sdk/CLEO_Utils.h
* Fixed performance of MemPatch
* Fixed off-by-one in StringPrintf
=> Utils fixes

.gitignore, tests/.cleo_tests_runner.txt, tests/cleo_tests/Cleo/004E.txt, tests/cleo_tests/Cleo/0051.txt, tests/cleo_tests/Cleo/0A92.txt, tests/cleo_tests/Cleo/0A93.txt, tests/cleo_tests/Cleo/0A94.txt, tests/cleo_tests/Cleo/0AA0.txt, tests/cleo_tests/Cleo/0AA1.txt, tests/cleo_tests/Cleo/0AA9.txt, tests/cleo_tests/Cleo/0AB3.txt, tests/cleo_tests/Cleo/0AB4.txt, tests/cleo_tests/Cleo/0DD5.txt, tests/cleo_tests/Cleo/2002.txt, tests/cleo_tests/Cleo/2003.txt, tests/cleo_tests/Cleo/testMission.txt, tests/cleo_tests/Cleo/testScript.txt, tests/cleo_tests/Math/2705.txt, tests/cleo_tests/Math/2706.txt
Added unit tests for almost all CLEO Core commands (except load_and_launch_mission_internal and save_this_custom_script)
=> Added unit tests for CLEO core commands

cleo_plugins/Audio/Audio.cpp, cleo_plugins/DebugUtils/DebugUtils.cpp, cleo_plugins/FileSystemOperations/FileSystemOperations.cpp, cleo_plugins/GameEntities/GameEntities.cpp, cleo_plugins/IniFiles/IniFiles.cpp, cleo_plugins/Input/main.cpp, cleo_plugins/Math/Math.cpp, cleo_plugins/MemoryOperations/MemoryOperations.cpp, cleo_plugins/Text/Text.cpp, cleo_sdk/CLEO_Utils.h
Plugin name moved from caption into message text.
=> Updated CLEO plugins version error message.

CHANGELOG.md, cleo_plugins/MemoryOperations/MemoryOperations.cpp, tests/cleo_tests/MemoryOperations/0AA5.txt, tests/cleo_tests/MemoryOperations/0AA6.txt, tests/cleo_tests/MemoryOperations/0AA7.txt, tests/cleo_tests/MemoryOperations/0AA8.txt
=> Set condition result in call function/method commands

CHANGELOG.md, source/CCustomOpcodeSystem.cpp, source/CCustomScript.cpp
* Updated script error messages to always include previous command
* Fixed previous command info persisting between scripts
* Added error when executing extra SCM info data as code
=> Error messages update

CHANGELOG.md, cleo_sdk/CLEO_Utils.h, source/CCustomOpcodeSystem.cpp
* Use macros from utils to handle params in CLEO core opcodes
* Fixed GetVarArgCount modifying processed params counter
=> Update core commands args processing

source/CleoBase.cpp
Make sure **GameEnd** and **ScriptsFinalize** callbacks are triggered on when exiting game and on crashes
=> Game cleanup fixes

cleo_sdk/CLEO.h, source/CCustomOpcodeSystem.cpp, source/CCustomOpcodeSystem.h, source/cleo.def, source/exports.cpp
Cherry picked from #421 and reworked
=> Added CLEO_CallNativeOpcode export

.github/workflows/release-preview.yml, .github/workflows/release.yml, .github/workflows/test-build.yml, CHANGELOG.md, CLEO5.vcxproj.filters, cleo_plugins/DebugUtils/DebugUtils.cpp, cleo_plugins/DebugUtils/DebugUtils.vcxproj, cleo_plugins/DebugUtils/DebugUtils.vcxproj.filters, cleo_plugins/DebugUtils/SA.DebugUtils.ini, cleo_plugins/DebugUtils/ScriptLog.cpp, cleo_plugins/DebugUtils/ScriptLog.h, cleo_sdk/CLEO.h, cleo_sdk/CLEO_Utils.h, source/CScriptEngine.cpp, source/CleoBase.cpp, source/OpcodeInfoDatabase.cpp, source/OpcodeInfoDatabase.h, source/ScmFunction.cpp, source/ScmFunction.h, source/ScriptUtils.h, source/cleo.def, source/exports.cpp
continuation of #369 
closes #433
=> Script logging (cont.)

cleo_plugins/DebugUtils/ScriptLog.cpp
crash happens in CRunningScript::LocateCharCommand
=> Fix crash after calling UpdateCompareFlag hook
