cleolibrary/CLEO5

- source/CScriptEngine.cpp
- source/FileEnumerator.h
Fix for backward compatibility with mod loader.
Fix for crash when script creation from file fails.
Briefly tested.
> Fix for backward compatibility with mod loader

- cleo_sdk/CLEO.h
- source/CCustomOpcodeSystem.cpp
- source/CScriptEngine.cpp
- source/FileEnumerator.h
Opcode 2001 returning only resolved paths
Added support for parent directory references "..\" in paths.
Replaced virtual path numbers with text keywords.
> Paths resolving updates

- cleo_sdk/CLEO.h
- source/CCustomOpcodeSystem.cpp
- source/CCustomOpcodeSystem.h
- source/CDebug.cpp
- source/CDebug.h
- source/CScriptEngine.cpp
- source/CleoBase.cpp
Text argument type names in error messages
Added pointer minimal value validation when reading or writing string params.
> Error messages update

- cleo_sdk/CLEO.h
- source/CCustomOpcodeSystem.cpp
Second commit is still discussable:
In previous CLEO versions it was possible to ignore some values returned by **cleo_return** as copied values count was determined by variable arguments count in **cleo_call**. So remaining arguments and varg-arg terminator byte were never used. 
This also could be used as way to prevent decompilation by removing or changing **cleo_return** var-arg terminator char.
> Cleo return arguments count check

- source/CCustomOpcodeSystem.cpp
`eax` register should be zeroed to correctly receive 1- and 2-byte values from the called function.
> fix function calls (opcodes 0AA5-0AA8)

- CHANGELOG.md
- cleo_plugins/IntOperations/IntOperations.cpp
Test script
```
{$CLEO .cs}
{$USE debug}
0000:
{$OPCODE 0B1E=2,sign_extend %1d% size %2d%}
debug_on
0@ = -42
1@ = allocate_memory size 4
// byte
write_memory address 1@ size 1 value 0@ vp false
2@ = read_memory address 1@ size 1 vp false
3@ = 2@
0B1E: sign_extend 3@ size 1
trace "1 BYTE: original value: %d, read value: %d, extended sign: %d" 0@ 2@ 3@
// 2 bytes
write_memory address 1@ size 2 value 0@ vp false
2@ = read_memory address 1@ size 2 vp false
3@ = 2@
0B1E: sign_extend 3@ size 2
trace "2 BYTES: original value: %d, read value: %d, extended sign: %d" 0@ 2@ 3@
// 3 bytes
write_memory address 1@ size 3 value 0@ vp false
2@ = read_memory address 1@ size 3 vp false
3@ = 2@
0B1E: sign_extend 3@ size 3
trace "3 BYTES: original value: %d, read value: %d, extended sign: %d" 0@ 2@ 3@
// 4 …
```
> New opcode sign_extend. Updates in read_memory opcode.

- CHANGELOG.md
- source/CCustomOpcodeSystem.cpp
- source/CScriptEngine.h
Implemented cleo_return_with opcode according to https://github.com/sannybuilder/dev/issues/263#issuecomment-1722089145
> New opcode cleo return with

- cleo_sdk/CLEO.h
- source/CCustomOpcodeSystem.cpp
Enabled using string array argument as module name in 0AB1.
> Fixed 0AB1 input argument count verification for string arrays.

- CHANGELOG.md
- CLEO5.vcxproj
- CLEO5.vcxproj.filters
- source/CCustomOpcodeSystem.cpp
- source/CCustomOpcodeSystem.h
- source/ScmFunction.cpp
- source/ScmFunction.h
ScmFunction moved to separate files
cleo_return_with now takes obligatory condition result argument
cleo_return_fail opcode
> Stack validation in cleo_return opcodes

- CHANGELOG.md
- cleo_sdk/CLEO.h
- source/CCustomOpcodeSystem.cpp
- source/CCustomOpcodeSystem.h
Test script
```
{$CLEO .cs}
0000:
20@ = allocate_memory 128
while true
cleo_call @GET_TEXT_L {args} 0 {result} 20@
cleo_call @GET_TEXT_L {args} 0 {result} 1@s
cleo_call @GET_TEXT_L {args} 0 {result} 3@v
print_formatted "literal~n~ptr: %s~n~short: %s~n~long: %s" {time} 3000 {args} 20@ 1@s 3@v
wait 3000
cleo_call @GET_TEXT_SHORT {args} 0 {result} 20@
cleo_call @GET_TEXT_SHORT {args} 0 {result} 1@s
cleo_call @GET_TEXT_SHORT {args} 0 {result} 3@v
print_formatted "short~n~ptr: %s~n~short: %s~n~long: %s" {time} 3000 {args} 20@ 1@s 3@v
wait 3000
cleo_call @GET_TEXT_LONG {args} 0 {result} 20@
cleo_call @GET_TEXT_LONG {args} 0 {result} 1@s
cleo_call @GET_TEXT_LONG {args} 0 {result} 3@v
print_formatted "long~n~ptr: %s~n~short: %s~n~long: %s" {time} 3000 {args} 20@ 1@s 3@v
wait 3000
cleo_call …
```
> Return strings support

- CHANGELOG.md
- source/CCustomOpcodeSystem.cpp
- source/CCustomOpcodeSystem.h
New opcode for removing memory blocks allocated with 0A8C from clean-up list used when starting new game/loading save.
Added virtual protect configuration to 0A8C, to allow hosting executable code.
```
2004=1, forget_memory %1d%
```
> forget_memory opcode

- cleo_sdk/CLEO.h
- source/CCustomOpcodeSystem.cpp
- source/CCustomOpcodeSystem.h
Updated string params handling.
> Parameters validation in call_function opcodes.

- CHANGELOG.md
- cleo_plugins/FileSystemOperations/FileSystemOperations.cpp
- cleo_plugins/FileSystemOperations/FileSystemOperations.vcxproj
- cleo_plugins/FileSystemOperations/FileSystemOperations.vcxproj.filters
- cleo_plugins/FileSystemOperations/FileUtils.cpp
- cleo_plugins/FileSystemOperations/FileUtils.h
- cleo_plugins/FileSystemOperations/Utils.h
- cleo_sdk/CLEO.h
- source/CCustomOpcodeSystem.cpp
- source/CCustomOpcodeSystem.h
- source/CGameVersionManager.cpp
- source/CGameVersionManager.h
- source/cleo.def
- tests/test_file_read_write.txt
Moved all file io stream opcodes to filesystem plugin.
New opcode read_block_from_file
New opcode get_file_position
Multiple bug fixes, parameters validation and error messages.
Implemented legacy mode for all file streams related opcodes.
Added test script testing all stream opcodes.
```
2300=2,get_file_position %1d% store_to %2d%
2301=3,read_block_from_file %1d% size %2d% buffer %3d%
```
> File related opcodes updates

- cleo_sdk/CLEO_Utils.h
- source/CCustomOpcodeSystem.cpp
- source/CCustomOpcodeSystem.h
- source/CScriptEngine.cpp
- source/CScriptEngine.h
test script:
```
{$CLEO .cs}
nop
wait 6000
0109: add_score 0 money 10
00BA: print_big 'BJ_05' time 2000 style 4
wait 2000
0109: add_score 0 money 10
0@s = 'UNITY'
00BA: print_big 0@s time 2000 style 4
wait 2000
0109: add_score 0 money 10
0@v = "SASO"
00BA: print_big 0@v time 2000 style 4
wait 2000
0109: add_score 0 money 10
allocate_memory 64 store_to 0@
0AD3: string_format 0@ format "%s" args "STAR"
00BA: print_big 0@ time 2000 style 4
wait 2000
terminate_this_custom_script
```
> String args support for legacy opcodes

- cleo_plugins/MemoryOperations/MemoryOperations.cpp
- cleo_sdk/CLEO_Utils.h
Tweaked 0A8C to restore original behavior of obtaining data from neighbor variables.
> Fixed opcodes 0A8D, 2401, 2402 types invalid data type restrictions.

- cleo_sdk/CLEO_Utils.h
//repro
```
{$CLEO .cs}
debug_on
int buf = allocate_memory 255
string_format buf "cleo:\\.cleo_config.ini"
if does_file_exist buf // returns false
then trace "success"
else trace "error"
end
terminate_this_custom_script
```
compiled: [repro-read-fs-bug.zip](https://github.com/cleolibrary/CLEO5/files/14468225/repro-read-fs-bug.zip)
> OPCODE_READ_PARAM_FILEPATH should return pointer to buffer with resolved filepath

- cleo_sdk/CLEO_Utils.h
All unit tests from `.cleo_tests_runner.txt` passed
> Fixed OPCODE_READ_PARAM_FILEPATH macro.

- CHANGELOG.md
- cleo_plugins/FileSystemOperations/FileSystemOperations.cpp
- cleo_plugins/FileSystemOperations/FileSystemOperations.vcxproj
- cleo_plugins/FileSystemOperations/FileSystemOperations.vcxproj.filters
- cleo_plugins/FileSystemOperations/FileUtils.cpp
- cleo_plugins/MemoryOperations/MemoryOperations.cpp
- tests/cleo_tests/FilesystemOperations/0A9E.txt
- tests/cleo_tests/FilesystemOperations/0AD7.txt
- tests/cleo_tests/FilesystemOperations/2301.txt
- tests/cleo_tests/FilesystemOperations/2302.txt
- tests/cleo_tests/MemoryOperations/2407.txt
Fixes https://github.com/cleolibrary/CLEO5/issues/58
> File related opcodes fixes. More tests.

- tests/cleo_tests/FilesystemOperations/0A9A.txt
- tests/cleo_tests/MemoryOperations/0A8C.txt
- tests/cleo_tests/MemoryOperations/0A8D.txt
- tests/cleo_tests/MemoryOperations/0A96.txt
- tests/cleo_tests/MemoryOperations/0A97.txt
- tests/cleo_tests/MemoryOperations/0A98.txt
- tests/cleo_tests/MemoryOperations/0AA4.txt
- tests/cleo_tests/MemoryOperations/0AC6.txt
- tests/cleo_tests/MemoryOperations/0AC7.txt
- tests/cleo_tests/MemoryOperations/0AC8.txt
- tests/cleo_tests/MemoryOperations/0AC9.txt
- tests/cleo_tests/MemoryOperations/0AE9.txt
- tests/cleo_tests/MemoryOperations/0AEA.txt
- tests/cleo_tests/MemoryOperations/0AEB.txt
- tests/cleo_tests/MemoryOperations/0AEC.txt
- tests/cleo_tests/cleo_tester.txt
Goals: 
* Focus on important things when writing unit tests. 
* Standardize test structure. 
Public API:
- `test(name: string, callback: int)`  -- creates new test suite (collection of unit tests)
- `it(expectation: string, callback: int)` -- creates new individual test focusing on testing one thing
- `before_each(callback: int)` -- registers a callback that runs before each unit test (test setup)
- `after_each(callback: int)` -- registers a callback that runs after each unit test (test teardown)
- `assert_eq(val1: int, val2: int)` - checks if two int values are equal, otherwise stops the test execution
- `assert_eqf(val1: int, val2: int)` - same as above, but for floats
- `assert_neq(val1: int, val2: int)` - checks if two int values are not equal, otherwise stops the test execution
- …
> CLEO testing library

- cleo_plugins/MemoryOperations/MemoryOperations.cpp
Pointers are already checked by get pointer param macros.
> Removed duplicated address checks from memory read/write opcodes.

- CHANGELOG.md
- cleo_plugins/Text/Text.cpp
- cleo_plugins/Text/Text.vcxproj
- cleo_plugins/Text/Text.vcxproj.filters
Gives way to draw script texts without need to create new GXT entries.
Test script:
```cpp
{$CLEO .cs}
nop
{$OPCODE 2605=-1,display_text_formated offset_left %1d% offset_top %2d% format %3d% args }
while true
wait 0
use_text_commands {state} true
float pos = 0.0
int idx
for idx = 0 to 59
pos += 7.0
set_text_scale {width} 0.3 {height} 0.9
int c = idx * 4
set_text_colour {rgb} c 255 c {alpha} 255
2605: display_text_formated {offset_left} 50.0 {offset_top} pos {format} "txt %d at %0.1f" {args} idx pos
end
end
terminate_this_custom_script
```
> New opcode display_text_formatted

- .github/workflows/main.yml
- .github/workflows/version.js
- CHANGELOG.md
- README.md
> release with multiple asi loader versions

- tests/cleo_tests/FilesystemOperations/0A9A.txt
- tests/cleo_tests/MemoryOperations/0A8C.txt
- tests/cleo_tests/MemoryOperations/0A8D.txt
- tests/cleo_tests/MemoryOperations/0A96.txt
- tests/cleo_tests/MemoryOperations/0A97.txt
- tests/cleo_tests/MemoryOperations/0A98.txt
- tests/cleo_tests/MemoryOperations/0AA4.txt
- tests/cleo_tests/MemoryOperations/0AC6.txt
- tests/cleo_tests/MemoryOperations/0AC7.txt
- tests/cleo_tests/MemoryOperations/0AC8.txt
- tests/cleo_tests/MemoryOperations/0AC9.txt
- tests/cleo_tests/MemoryOperations/0AE9.txt
- tests/cleo_tests/MemoryOperations/0AEA.txt
- tests/cleo_tests/MemoryOperations/0AEB.txt
- tests/cleo_tests/MemoryOperations/0AEC.txt
- tests/cleo_tests/Text/0AD3.txt
- tests/cleo_tests/Text/0AD4.txt
- tests/cleo_tests/Text/0ADB.txt
- tests/cleo_tests/Text/0ADE.txt
- tests/cleo_tests/Text/0ADF.txt
- tests/cleo_tests/Text/0AE0.txt
- tests/cleo_tests/Text/0AED.txt
- tests/cleo_tests/Text/2600.txt
- tests/cleo_tests/Text/2601.txt
- tests/cleo_tests/Text/2602.txt
- tests/cleo_tests/Text/2603.txt
- tests/cleo_tests/Text/2604.txt
- tests/cleo_tests/cleo_tester.inc
- match beta.7 & latest function spec
- add new `xit` helper to quickly disable a test(it->xit->it)
> update test framework to latest sb

- cleo_plugins/MemoryOperations/MemoryOperations.cpp
- tests/cleo_tests/MemoryOperations/0AA4.txt
> Enabled support of export index as argument in get_proc_address opcode

- source/CPluginSystem.cpp
Some plugins were listed twice due to search patterns overlap for `*.cleo` and `SA.*.cleo`
Displaying duplicated plugin warning name in original case.
```
15/06/2024 11:59:31.634 Listing CLEO plugins:
15/06/2024 11:59:31.635  - 'D:\GTA_SA\cleo\cleo_plugins\SA.Audio.cleo'
15/06/2024 11:59:31.635  - 'D:\GTA_SA\cleo\cleo_plugins\SA.DebugUtils.cleo'
15/06/2024 11:59:31.635  - 'D:\GTA_SA\cleo\cleo_plugins\SA.FileSystemOperations.cleo'
15/06/2024 11:59:31.635  - 'D:\GTA_SA\cleo\cleo_plugins\SA.IniFiles.cleo'
15/06/2024 11:59:31.635  - 'D:\GTA_SA\cleo\cleo_plugins\SA.Math.cleo'
15/06/2024 11:59:31.635  - 'D:\GTA_SA\cleo\cleo_plugins\SA.MemoryOperations.cleo'
15/06/2024 11:59:31.635  - 'D:\GTA_SA\cleo\cleo_plugins\SA.Text.cleo'
15/06/2024 11:59:31.636  - 'D:\GTA_SA\cleo\FileSystemOperations.cleo' …
```
> Fixed doubled listing plugin files.

- CHANGELOG.md
- cleo_plugins/MemoryOperations/MemoryOperations.cpp
- cleo_sdk/CLEO.h
- source/CCustomOpcodeSystem.cpp
- source/CScriptEngine.cpp
- source/CScriptEngine.h
- source/cleo.def
Enabled CLEO_GetScriptFilename to work with inactive scripts
0ABA moved to memory plugin
0ABA fixed to stop all threads with given name
Added `terminate_script ptr` opcode
Added SDK exports:
* CLEO_IsScriptRunning
* CLEO_TerminateScript
> Enabled CLEO_GetScriptFilename to return info from inactive threads.

- cleo_plugins/Audio/Audio.cpp
- cleo_plugins/Audio/C3DAudioStream.cpp
- cleo_plugins/Audio/CAudioStream.cpp
- cleo_plugins/Audio/CSoundSystem.cpp
- cleo_plugins/Audio/CSoundSystem.h
- cleo_plugins/Audio/SA.Audio.ini
Test script
```cpp
{$CLEO .cs}
wait 1000
AudioStream aStream = load_audio_stream {audioFileName} "http://uifserver.net/play/intro.mp3"
AudioStream.SetState(aStream, AudioStreamAction.Play)
terminate_this_custom_script
```
> Enabled support of network sources in audio stream opcodes.

- source/CScriptEngine.cpp
Temporary fix to keep ModLoader feeding CLEO scripts.
> Cleo scripts listing with modloader

- cleo_plugins/FileSystemOperations/FileSystemOperations.cpp
- tests/cleo_tests/FilesystemOperations/2305.txt
- tests/cleo_tests/cleo_tester.inc
> New get_file_write_time opcode

- cleo_plugins/MemoryOperations/MemoryOperations.cpp
Fixes problem found by Vital where it was impossible to get pointer of longstring variable.
Fixes problem found by 123nir where RZL trainer was throwing error due to declared-provided argument count missmatch in function/method call opcodes.
> Various fixes

- .github/workflows/main.yml
- cleo_plugins/Audio/Audio.cpp
- cleo_plugins/Audio/CAudioStream.cpp
- cleo_plugins/Audio/CAudioStream.h
- cleo_plugins/Audio/CSoundSystem.cpp
- cleo_plugins/Audio/CSoundSystem.h
- cleo_plugins/Audio/SA.Audio.ini
- examples/Audio_Demo.txt
Introduced separated default global volume settings for audio streams created from scripts in legacy mode.
Default type can be set in SA.Audio.ini
Added example scripts directory to cleo_readme. Added audio example script
> Keep default volume for audio streams in legacy scripts

- CHANGELOG.md
- cleo_plugins/Text/Text.cpp
- tests/cleo_tests/Text/2608.txt
Such basic operation should be possible in base CLEO without need for installing third party addons.
GET_STRING_LENGTH from NewOpcodes crashes with texts longer that 100 characters.
Same opcode from CLEO+ is hard caped to 128 characters.
Meanwhile CLEO5 supports up to 255 and pointer to cstring can store even longer texts.
https://discord.com/channels/911487285990674473/1226215589740286012/1267509561405734994
> Added get_text_length opcode

- source/CCustomOpcodeSystem.cpp
Fixes error occurring in Junior's Tuning Mod
In old Cleo target variables of not provided return values were just unmodified after call.
> Allowed more args in cleo_return than caller expected in legacy modes.

- cleo_plugins/Audio/CSoundSystem.cpp
- cleo_plugins/Text/CTextManager.cpp
- source/CCustomOpcodeSystem.cpp
- source/CPluginSystem.cpp
- source/CScriptEngine.cpp
- source/CleoBase.cpp
Added some empty lines to separate logical blocks in the log.
Cleaned up audio devices listing, fixed listing two devices as `default`.
Preview
```
09/09/2024 05:48:27.745 Starting new game, save slot: -1
09/09/2024 05:48:27.747 
09/09/2024 05:48:27.748 Listing audio devices:
09/09/2024 05:48:27.752  0: No sound
09/09/2024 05:48:27.752  1: Default
09/09/2024 05:48:27.752  2: Cyfrowe urządzenie audio (S/PDIF) (Urządzenie zgodne ze standardem High Definition Audio)
09/09/2024 05:48:27.752  3: AMD HDMI Output (AMD High Definition Audio Device)
09/09/2024 05:48:27.752  4: Głośniki (Urządzenie zgodne ze standardem High Definition Audio)
09/09/2024 05:48:27.752  Default device index: 4
09/09/2024 05:48:27.752 Selecting default audio device #4: Głośniki (Urządzenie zgodne ze standardem High …
```
> cleo.log improvements

- cleo_plugins/Audio/CSoundSystem.cpp
- source/CCustomOpcodeSystem.h
- source/CDebug.h
- source/CPluginSystem.cpp
- source/CPluginSystem.h
- source/CScriptEngine.cpp
- source/CleoBase.cpp
> Unloading CLEO plugins.

- .github/workflows/main.yml
with this change a new release can be run and created using GitHub UI. No need to create the tag in the local repository and push from the terminal. Just go to https://github.com/cleolibrary/CLEO5/releases/new, fill in the tag name, select set as a pre-release and click Publish.
> allow updating existing release when publishing

- source/CCodeInjector.h
- source/CGameMenu.cpp
- source/CGameVersionManager.cpp
- source/CGameVersionManager.h
- source/CleoBase.cpp
- source/CleoBase.h
- source/Mem.h
- source/dllmain.cpp
Added late initialization phase for installing on drawing finished hook.
Fixes #169
Fixes missing prints with SkyGFX mnod installed too.
> Updated OnDrawingFinished hook to not be overwritten by other mods.

- cleo_plugins/Audio/C3DAudioStream.cpp
- cleo_plugins/Audio/C3DAudioStream.h
- cleo_plugins/Audio/CSoundSystem.cpp
Parent class destructor was doing exactly same thing.
Added BASS version check and logging.
> Fix BASS_StreamFree called twice for 3d audio streams.

- source/CCustomOpcodeSystem.cpp
Function signature is
```CleoReturnGeneric(opcode, thread, returnArgs, returnArgCount, strictArgCount)```
> Fix 0AB2 return params in legacy scripts.

- tests/cleo_tests/FilesystemOperations/0A9A.txt
- tests/cleo_tests/FilesystemOperations/0A9B.txt
- tests/cleo_tests/FilesystemOperations/0AAB.txt
- tests/cleo_tests/FilesystemOperations/0AE4.txt
- tests/cleo_tests/FilesystemOperations/0AE5.txt
- tests/cleo_tests/FilesystemOperations/0B00.txt
- tests/cleo_tests/FilesystemOperations/0B01.txt
- tests/cleo_tests/FilesystemOperations/0B02.txt
- tests/cleo_tests/FilesystemOperations/0B03.txt
- tests/cleo_tests/FilesystemOperations/0B04.txt
- tests/cleo_tests/FilesystemOperations/0B05.txt
Not using `.cleo.log` as input file in tests, as it was randomly in use.
> Added unit test for file operation opcodes.

- cleo_plugins/DebugUtils/DebugUtils.cpp
- cleo_plugins/DebugUtils/ScreenLog.cpp
- cleo_plugins/DebugUtils/ScreenLog.h
Do not show log messages from previous game session in new session.
> Clear screen log on new game start

- tests/cleo_tests/FilesystemOperations/0AE5.txt
- tests/cleo_tests/FilesystemOperations/0B00.txt
- tests/cleo_tests/FilesystemOperations/0B01.txt
- tests/cleo_tests/FilesystemOperations/0B02.txt
- tests/cleo_tests/FilesystemOperations/0B03.txt
- tests/cleo_tests/FilesystemOperations/0B04.txt
- tests/cleo_tests/FilesystemOperations/0B05.txt
- tests/cleo_tests/IniFiles/0AF0.txt
- tests/cleo_tests/IniFiles/0AF1.txt
- tests/cleo_tests/IniFiles/0AF2.txt
- tests/cleo_tests/IniFiles/0AF3.txt
- tests/cleo_tests/IniFiles/0AF4.txt
- tests/cleo_tests/IniFiles/0AF5.txt
Added IniFiles unit tests
Added cleanup steps to file opcode unit tests
> More unit tests

- tests/.cleo_tests_runner.txt
- tests/cleo_tests/.Compile_All.bat
- tests/cleo_tests/cleo_tester.inc
> Unit tests log style updates.

- cleo_plugins/FileSystemOperations/FileSystemOperations.cpp
**move_file**
Fixed returning success on non existing path
Fixed returning success on directory
Fixed file being inaccessible for other opcodes even after game restart
**move_directory**
Fixed returning success on non existing path
Fixed returning success on file
**copy_directory**
Fixed returning success on non existing path
Used std::filesystem to handle copying directory contents
> File handling opcodes fixes

- cleo_sdk/CLEO_Utils.h
- tests/cleo_tests/FilesystemOperations/0A9A.txt
- tests/cleo_tests/FilesystemOperations/0AAB.txt
- tests/cleo_tests/FilesystemOperations/0AE4.txt
- tests/cleo_tests/FilesystemOperations/0AE5.txt
- tests/cleo_tests/FilesystemOperations/0B00.txt
- tests/cleo_tests/FilesystemOperations/0B01.txt
- tests/cleo_tests/FilesystemOperations/0B02.txt
- tests/cleo_tests/FilesystemOperations/0B03.txt
- tests/cleo_tests/FilesystemOperations/0B04.txt
- tests/cleo_tests/FilesystemOperations/0B05.txt
- tests/cleo_tests/IniFiles/0AF0.txt
- tests/cleo_tests/IniFiles/0AF1.txt
- tests/cleo_tests/IniFiles/0AF2.txt
- tests/cleo_tests/IniFiles/0AF3.txt
- tests/cleo_tests/IniFiles/0AF4.txt
- tests/cleo_tests/IniFiles/0AF5.txt
In case of filepath with duplicated separators some of Windows APIs tend to set last error variable to "invalid path", but access intended file anyway.
Remove doubled separators during path normalization, so CLEO internal paths comparisons can not be fooled by cases like this.
> Filepaths double separators handling

- cleo_plugins/DebugUtils/DebugUtils.cpp
Make script break point message flashing, so it does not look like game froze.
> Flashing of debug break message.

- cleo_plugins/Audio/C3DAudioStream.cpp
- cleo_plugins/Audio/CAudioStream.cpp
- cleo_plugins/Audio/CAudioStream.h
- cleo_sdk/CLEO.h
- examples/Audio_Demo.txt
- source/CleoBase.cpp
Due to adding virtual functions to the audio stream class VMT pointer was added to the data layout. This caused stream handle (address) no longer pointing on property containing underlying BASS stream pointer.
Updated so more advanced scripts still can work with BASS as in CLEO4.
Unit tests working, audio demo script works too.
> Make audio streams handle work as in cleo4

- cleo_plugins/DebugUtils/DebugUtils.cpp
- cleo_plugins/FileSystemOperations/FileSystemOperations.cpp
- cleo_sdk/CLEO_Utils.h
- source/CCustomOpcodeSystem.cpp
Fixed crashes when invalid formatted string/params are provided to some opcodes.
> Fix trace and breakpoint opcodes crashing

- CLEO5.vcxproj
- cleo_plugins/Text/CTextManager.cpp
- cleo_sdk/CLEO_Utils.h
- source/CCodeInjector.cpp
- source/CCustomOpcodeSystem.cpp
- source/CDebug.cpp
- source/CDebug.h
- source/CScriptEngine.cpp
- source/CleoBase.cpp
Automatic adding separator line to .cleo.log if frame render occur since last log entry.
Removed outputting text formatting sequences like `~r~` to log file. Logging `~n~` as actual new line.
Logging last and previous opcodes as FFFF if no script was executed.
> Cleo log improvements

- cleo_plugins/MemoryOperations/MemoryOperations.cpp
Can it backfire in any way? Plugin compiled in debug configuration throws similar exceptions\error messages when stack pointer is left modified.
Does it make sense to allow scripts in legacy mode to not pop after call?
> Stack pointer validation for call function/method opcodes

- source/CCodeInjector.h
- source/CCustomOpcodeSystem.cpp
- source/CDebug.cpp
- source/CDmaFix.cpp
- source/CGameMenu.cpp
- source/CPluginSystem.cpp
- source/CScriptEngine.cpp
- source/CleoBase.cpp
- source/CleoBase.h
- source/dllmain.cpp
Removed GetInstance() in favor of straight CleoInstance use.
Added _Orig suffix to all variables storing original hook addresses.
> Refactoring

- tests/cleo_tests/FilesystemOperations/0A99.txt
- tests/cleo_tests/cleo_tester.inc
Fixed failing 0A99.
Added more test scenarios.
> 0A99 tests rewritten

- cleo_plugins/DebugUtils/DebugUtils.cpp
- cleo_plugins/DebugUtils/DebugUtils.vcxproj
- cleo_plugins/DebugUtils/DebugUtils.vcxproj.filters
- cleo_plugins/DebugUtils/SA.DebugUtils.ini
- cleo_plugins/DebugUtils/ScriptLog.h
- examples/Limits_Info.txt
200k was enough for example script, but let's not create something that lags
> Added checks for scripts stuck in dead loop.

- cleo_plugins/Text/Text.cpp
- examples/Screen_Drawing.txt
Apparently **CTheScripts::NumberOfIntroTextLinesThisFrame** is cleared on every script processing, not once peer render frame.
This caused GXT labels generated by multiple scripts to not be unique.
> Fixed display_text_formatted texts overwriting themself

- source/CScriptEngine.cpp
Some opcodes relay on contents of params already read into opcodeParams array. GetScriptStringParam should not affect it.
> Fixed GetScriptStringParam hook to not alter state of opcodeParams array.

- cleo_plugins/DebugUtils/DebugUtils.cpp
- cleo_plugins/DebugUtils/DebugUtils.vcxproj
- cleo_plugins/DebugUtils/DebugUtils.vcxproj.filters
Handle key formatting sequences in same way as other opcodes do. Currently `~k~` of `~k~~PED_FIRE~` is ignored and game draws button icons instead of textual names.
> Translate key names in debug prints

- CHANGELOG.md
- cleo_plugins/Math/Math.cpp
- examples/Homie_Help.txt
- source/CCustomOpcodeSystem.cpp
- tests/cleo_tests/Math/2705.txt
- tests/cleo_tests/Math/2706.txt
- tests/cleo_tests/Math/2707.txt
- tests/cleo_tests/Math/2708.txt
- tests/cleo_tests/cleo_tester.inc
added **pick_random_int**
added **pick_random_float**
added **pick_random_text**
added **random_chance**
> New randomization opcodes

- cleo_plugins/Text/CTextManager.cpp
- source/CCustomOpcodeSystem.cpp
- source/CScriptEngine.cpp
- source/CScriptEngine.h
- source/cleo_config.ini
cleo_config.ini now has option to enable legacy scripts modes for native scripts (main.scm).
Unified way of queering script version (with CLEO_GetScriptVersion).
Removed duplicated assignments of script version and debug mode properties, as these are already handled by CCustomScript constructor.
To test legacy modes in main script use:
`$a = pow {number} 1 {power} 2.0`
Number argument is supposed to be float, error message is not displayed in legacy modes.
> Legacy modes support for native scripts

- CHANGELOG.md
- cleo_sdk/CLEO.h
- cleo_sdk/CLEO_Utils.h
- source/CGameVersionManager.cpp
- source/cleo.def
Removed word "error" suggesting CLEO's error, while it usually reports bugs in user's scripts.
Fixes #270
> Added CLEO version info to error message boxes.

- source/CGameVersionManager.cpp
- source/CGameVersionManager.h
- source/CleoBase.cpp
- source/CleoBase.h
Instead of function body hook calls to it.
Fixes #266
> DrawingFinished hook updated.

- cleo_plugins/IniFiles/IniFiles.cpp
Commands **read_int_from_ini_file** and **read_float_from_ini_file** called from scripts in legacy mode now returns success and value 0 in case of invalid data inside ini file.
Fixes #281
Test script.
```
{$CLEO .cs}
//set_current_directory 1
write_int_to_ini_file {value} 42 {path} "test.ini" {section} "t" {key} "iVal"
write_float_to_ini_file {value} 42.0 {path} "test.ini" {section} "t" {key} "fVal"
//write_string_to_ini_file {value} "forty two" {path} "test.ini" {section} "t" {key} "sVal" // CLEO4 crash
while true
wait 100
int iVal = 123
int iResult = false
if
iVal = read_int_from_ini_file {path} "test.ini" {section} "t" {key} "iVal"
then
iResult = true
end
float fVal = 123
int fResult = false
if
fVal = read_float_from_ini_file {path} "test.ini" {section} "t" {key} "fVal"
then
fResult = …
```
> Legacy behavior for INI read int/float when value does not contain number

- cleo_plugins/MemoryOperations/MemoryOperations.cpp
- source/CScriptEngine.cpp
Calling **terminate_all_scripts_with_this_name** with the name that matches a custom script leads to nasty bugs. Native implementation moves custom script from active queue to inactive one. If a new script is now spawned (in any way: reloading the game, calling start_new_script, or triggering an external script), this struct will be picked from the inactive queue (with **bIsCustom** still set). It may cause all sorts of unexpected behavior, from CLEO5 warnings, to game crashes. See the repro script:
```
{$CLEO .cs}
script_name 'help'
while true
wait 0
if 
test_cheat "repr"
then
terminate_all_scripts_with_this_name 'HELP' // current script is marked as inactive
0ace: "the game is screwed, don't try to load another save"
end
end
```
after using "REPR" cheat and loading another save the game …
> custom implementation for terminate_all_scripts_with_this_name

- CHANGELOG.md
- cleo_plugins/FileSystemOperations/FileSystemOperations.cpp
- tests/cleo_tests/FilesystemOperations/0AD7.txt
Opcode reads until line feed, but line feed is included in the result. When I was doing some other quick test with file as input data it took me by surprise. It is also problematic as in most cases user do not want the line feed characters and there is no easy way to get rid of them in script.
DYOM also has bug where import objective texts from file feature adds unwanted "?" character at the end of every text. I'm not sure if this is DYOM's bug or maybe that feature worked differently in CLEO3.
> Update read_string_from_file to not include line feed

- CHANGELOG.md
- cleo_plugins/IniFiles/IniFiles.cpp
- cleo_sdk/CLEO.h
- cleo_sdk/CLEO_Utils.h
- source/CCustomOpcodeSystem.cpp
- source/CScriptEngine.cpp
- source/cleo.def
- tests/cleo_tests/IniFiles/0AF1.txt
- tests/cleo_tests/IniFiles/0AF3.txt
- tests/cleo_tests/IniFiles/0AF5.txt
- tests/cleo_tests/IniFiles/2800.txt
- tests/cleo_tests/IniFiles/2801.txt
- tests/cleo_tests/cleo_tester.inc
* calling [WritePrivateProfileStringA ](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-writeprivateprofilestringa) with NULL for key or value allows deleting the whole section or the key respectively. Since 0 is a valid int/float value, only allow `0` in value position for `write_string_to_ini_file` - ONLY in CLEO 4.4 compatible mode
* updated / fixed tests. use of "gta_sa.exe" in some tests caused my local gta_sa.exe to be corrupted as I run the game from gta_sa_compact.exe.
* added new SDK method to set script compat mode
* updated test framework with new `it_cs4` function to test code in CS4 compat mode
* added 2 new commands in ini extension: [DELETE_SECTION_FROM_INI_FILE ](https://library.sannybuilder.com/#/sa/script/extensions/ini/2800) and …
> update INI commands to allow deleting sections or keys from ini files

- cleo_plugins/MemoryOperations/MemoryOperations.cpp
- tests/cleo_tests/MemoryOperations/0AA8.txt
- tests/cleo_tests/cleo_tester.inc
Enables **Turn Indicators** mod to work in cs4 mode
https://www.gtagarage.com/mods/show.php?id=14581 to work
That script misuses call method opcode hardly
> Allow call_method_return with nullptr 'this' param

- source/CDebug.cpp
- source/CScriptEngine.cpp
Example log output:
`03/03/2025 22:41:58.975 Error during loading of custom script c:\users\[redacted]\documents\gta san andreas user files\test.cs occured.`
> Censoring user name in logs

- .github/workflows/main.yml
if someone needs tests (who?) they can download them using this batch script
```
curl -L https://github.com/cleolibrary/CLEO5/archive/refs/heads/master.zip -o CLEO5-master.zip
"C:\Program Files\7-Zip\7z.exe" x CLEO5-master.zip -aoa
cp -r CLEO5-master/tests cleo_tests
rm CLEO5-master.zip
rm -r CLEO5-master
```
> don't include tests in release archive

- CHANGELOG.md
- cleo_plugins/Audio/Audio.vcxproj
- cleo_plugins/Audio/Audio.vcxproj.filters
- cleo_plugins/Audio/C3DAudioStream.cpp
- cleo_plugins/Audio/C3DAudioStream.h
- cleo_plugins/Audio/CAudioStream.cpp
- cleo_plugins/Audio/CAudioStream.h
- cleo_plugins/Audio/CInterpolatedValue.h
- cleo_plugins/Audio/CSlidingParam.h
- cleo_plugins/Audio/CSoundSystem.cpp
- cleo_plugins/Audio/CSoundSystem.h
- examples/Audio_Demo.txt
- updated distance decay for 3d CLEO sounds to match behavior of in-game sounds
- implemented proper support for 3d CLEO sounds source size
- CLEO sounds volume is now affected by wide screen and fades in same way as in-game sounds
- updated "Audio_Demo" example script
- Introduced CSlidingParam class to not repeat same code for each stream parameter supporting transitions (speed and volume)
> Implemented proper distance decay and source size handling for 3d sounds.

- source/CCodeInjector.h
- source/CCustomOpcodeSystem.h
- source/CDmaFix.h
- source/CGameMenu.h
- source/CScriptEngine.h
Removed VInjectible class as polymorphism was not used in any way, so we had virtual tables for nothing.
> Removed VInjectible.

- CLEO5.vcxproj
- cleo_plugins/Audio/Audio.vcxproj
- cleo_plugins/DebugUtils/DebugUtils.vcxproj
- cleo_plugins/FileSystemOperations/FileSystemOperations.vcxproj
- cleo_plugins/GameEntities/GameEntities.vcxproj
- cleo_plugins/IniFiles/IniFiles.vcxproj
- cleo_plugins/Math/Math.vcxproj
- cleo_plugins/MemoryOperations/MemoryOperations.vcxproj
- cleo_plugins/Text/Text.vcxproj
Reordered preprocessor definitions so shared properties are listed first.
> Remove unnecessary preprocessor definitions.

- CLEO5.vcxproj
- cleo_plugins/Audio/Audio.vcxproj
- cleo_plugins/DebugUtils/DebugUtils.cpp
- cleo_plugins/DebugUtils/DebugUtils.vcxproj
- cleo_plugins/FileSystemOperations/FileSystemOperations.cpp
- cleo_plugins/FileSystemOperations/FileSystemOperations.vcxproj
- cleo_plugins/FileSystemOperations/FileUtils.cpp
- cleo_plugins/GameEntities/GameEntities.vcxproj
- cleo_plugins/IniFiles/IniFiles.cpp
- cleo_plugins/IniFiles/IniFiles.vcxproj
- cleo_plugins/Math/Math.vcxproj
- cleo_plugins/MemoryOperations/MemoryOperations.cpp
- cleo_plugins/MemoryOperations/MemoryOperations.vcxproj
- cleo_plugins/Text/Text.cpp
- cleo_plugins/Text/Text.vcxproj
- cleo_sdk/CLEO.h
- cleo_sdk/CLEO_Utils.h
- source/CCustomOpcodeSystem.cpp
- source/CDebug.cpp
- source/CScriptEngine.cpp
- source/dllmain.cpp
- source/exports.cpp
Fixed warnings about insecure runtime functions like strcpy. 
Enabled warnings as errors.
> Fix warnings and remove _CRT_SECURE_NO_WARNINGS from project settings.

- source/CCodeInjector.h
- source/Mem.h
Added comparation operators to memory_pointer.
Cleaned up original address retrieval for MemJump and MemCall functions.
Original addresses reported in cleo.log did not changed.
> Fixed recursion loop in memory_pointer assign operator

- source/CScriptEngine.cpp
- source/CScriptEngine.h
Cleaned up CScriptEngine::RemoveCustomScript.
Updated so it is always used for custom scripts removal.
Fixed CLEO's unregister callback not always called for custom scripts.
> Updates in custom script removal

- cleo_plugins/Text/Text.cpp
- cleo_sdk/CLEO_Utils.h
Fix MemPatch Apply bug.
Instead re-implementing contents of CText::Get just call it. If any other mod installed hook there it will be called too.
> Late hooking of CText.Get. Respect already installed hooks.

- cleo_plugins/Audio/Audio.cpp
- cleo_plugins/DebugUtils/DebugUtils.cpp
- cleo_plugins/FileSystemOperations/FileSystemOperations.cpp
- cleo_plugins/IniFiles/IniFiles.cpp
- cleo_plugins/Math/Math.cpp
- cleo_plugins/MemoryOperations/MemoryOperations.cpp
- cleo_sdk/CLEO.h
- source/CCustomOpcodeSystem.cpp
- source/CCustomOpcodeSystem.h
* Removed (never tested) plain C support.
* Renamed ScriptOpcodeProcess* callbacks to fit general xBefore, xAfter naming convention. 
* Removed legacy typedefs.
* Merged duplicated _pOpcodeHandler and CustomOpcodeHandler typedefs.
> CLEO.h refactor

- CHANGELOG.md
- cleo_plugins/Audio/Audio.cpp
- cleo_plugins/Audio/C3DAudioStream.h
- cleo_plugins/Audio/CAudioStream.h
Print warning when plain audio stream is used as parameter in 3d audio stream commands
> Added warning about stream type to 0AC2-0AC5 commands

- CHANGELOG.md
- cleo_plugins/MemoryOperations/MemoryOperations.cpp
- cleo_plugins/MemoryOperations/MemoryOperations.vcxproj
- cleo_plugins/MemoryOperations/MemoryOperations.vcxproj.filters
- cleo_plugins/MemoryOperations/SA.MemoryOperations.ini
- cleo_sdk/CLEO.h
- source/CScriptEngine.cpp
Default limit of 2000 allocations is about minute of calling **allocate_memory** each frame without releasing
Added more details about cleanup in cleo.log
```
23/07/2025 03:17:42.687 Cleaning up 7 allocated memory blocks:
23/07/2025 03:17:42.687  1 block (0.39 kB) in script 'dm_enh' from 'DYOM_Enhancer.cs'
23/07/2025 03:17:42.687  5 blocks (10.52 kB) in script 'main' from 'scr.scm'
23/07/2025 03:17:42.687  1 block (0.03 kB) in script 'noname' from 'scr.scm'
23/07/2025 03:17:42.687 
23/07/2025 03:17:42.687 Cleaning up 1 loaded libraries:
23/07/2025 03:17:42.687  modloader\$f92 limit adjuster\$fastman92limitadjuster.asi
```
> Added warning about memory allocation limits
